### ISSUE TITLE
Timeout doesn't seem to work?

### ISSUE THREAD

**Issue by andreyrd** [emilioschepis/wait-for-endpoint#1]
I'm using this like so:
```
      - name: 'Wait for WebApp to become available'
        uses: emilioschepis/wait-for-endpoint@v1.0.0
        with:
          url: ${{ env.AZURE_WEBAPP_URL }}
          method: GET
          expected-status: 200
          timeout: 60000
          interval: 2000
```

So I would think it would timeout after 60 seconds, but my action ran for more than 7 minutes and I had to cancel it.
If I expand the step, it does show the error, but the action never exits. Does `main()` need an `await` at the top level maybe?
